61 list action menu
chingu-voyage4/Geckos-Team-13 pull request #88
Opened 2018-03-21 17:57 UTC by zealousAnemone

Added list action menu. It can be toggled by clicking the ellipses on the list. Only some of the options open submenus as some necessary functionality isn't there yet.

2018-03-22 00:26 UTC, ghost requested changes
First, this looks amazing! And you also got a ton done. 
Most of my comments are minor and don't have to be implemented if you disagree. 

1. Can we shift the menu to the right so that it falls under the ellipses?

2. I think we could probably simplify this component so that submenus were separate components. I think it could all still be wrapped into one PR but the render method might read a little cleaner. 
 
3. Related to that, the logic can be moved up (out of render). By this I mean the if/else statements checking state.

4. Lines 12 and 13 should be combined to look like this:

this.state = { 
    follow: false, 
    menu: "main"
}

and then moved above the bindings.

2018-03-22 03:10 UTC, zealousAnemone commented
Thanks @tiffanydevine ! Working on your suggested changes.

2018-03-22 17:28 UTC, tiffanydevine commented
Ignore 3rd comment.

2018-03-22 18:22 UTC, zealousAnemone commented
@tiffanydevine the one about moving the logic?

2018-03-22 19:03 UTC, tiffanydevine commented
Yes

2018-03-23 00:04 UTC, tiffanydevine commented on src/components/ListMenu.js
> +class ListMenu extends React.Component {
This is super small but you can remove React from React.Component since you pulled it out in the import

2018-03-23 16:27 UTC, closed without merging